apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-kale
  namespace: eks-example
  annotations:
    volume.beta.kubernetes.io/storage-class: "gp2"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
