---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUSCwrQ1hu0gtnmHJpiGPi553B+7MwDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMTkxMTI3MTQ0MjAwWhcNMjQxMTI1MTQ0MjAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    AKzRhaC92gku2f29syZCYtc6FqeZur8sUNrt70lCUPz30teUCI2pJEYsu1K2EYvw
    zvmlyziFWOrwag+plRTKgWPOabWfS4Saxx2OJvcuSmmh3hnwzt3EfeRMcYE3Mrt1
    jRfCT5wFEUA1/o/N9dl19sNNZ7Dyvgap9P3laVjK4i3T60h6wmknOZlGnJuVy8J/
    D4CLQNkRTwAqkQvEZQ1BjR/88cNpKNoBnrkq6dsgw3XdX7upFP8+4riz66qgFRLW
    AK3RETvy1XMcIi6Pvq96NBlnHChE13NRE4rGYUE7XpxkNq1IV0apVph9gwGzMg7A
    XR/d3x0ubsgzw0M319r8U0rkk2KRHWbroV5WCT0Dwo6+7TmRc+g4z2hx7DXhquvb
    BCUPjC24nNKfkUWgmbR4xe8Ie5MS4dx76fMPEL8blUsNQgEU/jq/7J1y93DJA7Ly
    Li89OnOfa8bzQdTlg1WnCKAJDEu+U+pNF2442tcY1lRfwtAh8IU/yXtFtK5mTZh8
    4qnmIZ4W+GGTGzY3/wpUQgKbRhl3BcpfVnojKU4Jw3oNUoP6UHFT0BlU4oD+NdPv
    NSjXMHMzS0rskqU9YWsg0Un8q3qwwb8NsfVLsurzHy+aEv670V191E6L3TQE12s7
    2ZZoB+2wEDwOnEECPv3d+CENA4Gmgs+qtPZul+iWR4MVAgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRjzBSbL6HnMrs9
    UbIFbKCDp6aiHjANBgkqhkiG9w0BAQ0FAAOCAgEAJi63Dx6ktP9/7+UelyoxEVxB
    yKoreBHSyg/YDpF2oEPotKK0tlujpM9HBthcqeWJmT7KEnsGfpMoEZAmUwgFSla8
    92XZS2eRCZKkSM//MSHDXwDpnD//WvknjrzQUtDj2rhQjajFTjhzM0KoTWNH/1ZQ
    Eie/vfgVGLvfKbvuWZnZKI3sv/rfR/tM3W/NSJNzgD0ubnt2UC+HWaO94Ay7WeoY
    Pf3HQ0OflRhM3fMd3ZJt+6UBZgANuDCIGJwnx8eq2D5RzrIajsHM0bfhLB3x8vri
    4AKSJQDOFcNImm/J+gpdamg3UjKP2+5U7PWv9ep/sx4Q1NS90nv3F3MP/LugWcyA
    ZQd1etJPgz2inD4J+NYTiFZwltF0gMzDCfMwKzOGi5W3YT+ruHSwQDivGXVeW6f4
    V0VYT7KiKOSv4G2A3vyk8hvcOSYGdT5PeixpJXNaF1fIF3QVcKQcrTFayVjnuRlU
    nNiMiwkHwOfBCfqo8899d2B2caLSmMnfBMDD+jxLlmYgxnijIbzucQeeOzAkqToD
    LHe2jzmatLn2wLcRhVyvVgcPyxwzrNRCAhmBq1CMovfnHYSl5jm9YNUNeiJtlAtM
    tPDPvP1niCu9p7DkYMyPAyohZSxmgjKWl/6A8n2KQO8K7y8glICL7vIC73tM/u9l
    la7ZdSbZV+e1g6ojPuk=
    -----END CERTIFICATE-----
    
