---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUQvWmxOVhAsUU7qu/cbuWat3hYw8wDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMTkxMTEzMTQyNDAwWhcNMjQxMTExMTQyNDAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    AKp69HVGa4HMitnt/OaTHfpwRr70sRMsL2DUqNnp7vCXGKbO03Wpqu1ueQ4rIj77
    qdxUY4yx30ouH4nBKjPOm5hpAkUdKLoFTG0vLqpGfQLCId6rmKyi6F38VZF5SELt
    Cj1TLkAO0AfThKFHDhC4fHZzR/tBtnJsLY/vPKReQBvJe41329ZBz+IV6wscwIV9
    jA/CF1PmXsG6MVJXsEILVvz4FLJBICCPMyQkt5XmRZYF87pI3rU/pyuURoLQ2Dbx
    ItdMFzuHyCTfLaLOqOc5E/r+F0utqcp0sPZW8Vp9Rqt6fuqg+ln3R1HVgVPMGI8J
    qfvexoCAM3sLYBHoW9MvvnY5nydpEkPcPsxGzu7vJT9VUkhbVyv3RcMepcHXt98i
    6GJJloEpCLYQUO1Tosh5y1xENbbObP4v8Tr2aehrExowL2+FRU3zbpdaS/kCGCru
    nM3LFK/KVGlIr+HqkMKb3gya0MzPZeI5P4hGd0EnEEW5sseglA7/nH98JW4psRT3
    a3LnXyikd44/do/iEV50TgXfjw3+4cgeDIL8qeZl7tlc1AfgCq5LHLjvejStLSOQ
    2RZHFjI1LW0/wM3IUaFpW/nkqrJ4aZbHH7w6I0+or6P6ltTFoC0fERFFoMUeBJpV
    DwKM1d8gvSBsyN9f8SGN2yxPYqsdFl250aDzQ6LNDDRLAgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQc5Wg3WJcD2ACj
    9auNLFfnb/wuWjANBgkqhkiG9w0BAQ0FAAOCAgEAOdHgQVa4XwJhj0TlrrMFfOE4
    Tri27mN2mmH7zeHHrbiiQHcjKsyHpsCWuV5ITYIreRyddsUyr/OJ8Jwhgp26nxJo
    a2d3Gr3CYzHfwPDWFZpTBwaOCPvJROnxdbMHap+Lyovyim9MtWuQ5mCseiihUQxE
    3zCq1r+B048U5HcON4GcWOhx0loqMLMKq9LPWiXK5EAJVmFRUX4hAqCOjeSBgg7O
    a0P4ArAZ64dSw+m0GMQh434j89QnHO/FgvGnsLflW7r02Zqp0n8GZfP/gty7J6ml
    so4OIJaHCgPYEmyLvhFB12lXH+u5hu2692NolW6Q+w566RUbmZP0+oERnPTSJGVu
    8W1tibV99NkctOc6nnhOhxtJMLPMRmCqCVtt2fhAYdZRsiIe9UTRJovIhwxNV6m4
    ZKaOb+/UvbQbBFO/sxZ85sa7ep6PEcmMJsg7fk+0hc8B13FFX1yywHY03yh3GfOa
    3qugIt+hUAPuEZ0ID9lDQVWwE+RAnxuUrihGH/GrDiRg/JEkWtkWop8a+xRRn0JZ
    YDnsko5SPuEIt3mOGG0JrYO+xC4syrUHPYyvlJpWTfZLMtDJuFjJyjIR6V7pcyTW
    q6w6S3+OOfCBrHjFr9sx2i65GMk6xLHgMeETrsC8PVV5N59N74ySF38d+4Pm7+8M
    0iXf2Cua9WHDdio6A8A=
    -----END CERTIFICATE-----
    
